id: I40B6F4AA
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W30416
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2023-12-16T17:13:50.675968'
last_modified: '2023-02-01T00:00:00+00:00'
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30416
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30416
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཉག་འཇམ་དབྱངས་གྲགས་པའི་རང་རྣམ།
  languages:
  - bo
  author: རི་ཁྲོད་ཀྱི་དབང་ཕྱུག་འཇམ་དབྱངས་གྲགས་པ།
statistics: null
quality: null
bases:
  I1PD28133:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD28133
      total_pages: 362
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1PD28133.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
  info_url: null
license: CC0
